variables = {
    'IQ_TOTAL_REV': 'Total Revenue',
    'IQ_COST_REV': 'Cost of Revenues',
    'IQ_GP': 'Gross Profit',
    'IQ_SGA': 'SG&A Expense',
    'IQ_RD_EXP': 'R&D Exp',
    'IQ_RD_EXP_FN': 'R&D Exp 2',
    'IQ_DA': 'Depreciation & Amortization',
    'IQ_TOTAL_OTHER_OPER': 'Other Operating Expense, Total',
    'IQ_TOTAL_OPER_EXPEN': 'Total Operating Expenses',
    'IQ_OPER_INC': 'Operating Income',
    'IQ_NET_INTEREST_EXP': 'Net Interest Expense',
    'IQ_EBT_EXCL': 'EBT Excluding Unusual Items',
    'IQ_TOTAL_UNUSUAL': 'Total Unusual Items',
    'IQ_EBT': 'EBT',
    'IQ_MINORITY_INTEREST_IS': 'Minority Interest in Earnings',
    'IQ_NI': 'Net Income',
    'IQ_NI_NORM': 'Net Income, Normalized',
    'IQ_BASIC_EPS_INCL': 'Basic EPS',
    'IQ_BASIC_EPS_EXCL': 'Basic EPS Excluding Extra Items',
    'IQ_EBITDA': 'EBITDA',
    'IQ_EBIT': 'EBIT',
    'IQ_EFFECT_TAX_RATE': 'Effective Tax Rate',
    'IQ_PAYOUT_RATIO': 'Payout Ratio',
    'IQ_CASH_ST_INVEST': 'Cash and ST Investments',
    'IQ_TOTAL_RECEIV': 'Total Receivables',
    'IQ_INVENTORY': 'Inventory',
    'IQ_PREPAID_EXP': 'Prepaid Expenses',
    'IQ_OTHER_CA': 'Other Current Assets, Total',
    'IQ_DEF_TAX_ASSETS_CURRENT': 'Deferred Tax Assets, Current',
    'IQ_TOTAL_CA': 'Total Current Assets',
    'IQ_NPPE': 'Net PPE',
    'IQ_AD': 'Accumulated Depreciation',
    'IQ_GW': 'Goodwill',
    'IQ_OTHER_ASSETS': 'Other Assets, Total',
    'IQ_TOTAL_ASSETS': 'Total Assets',
    'IQ_AP': 'Accounts Payable',
    'IQ_AR': 'Accounts Receivable',
    'IQ_ST_DEBT': 'Short Term Debt',
    'IQ_OTHER_CL': 'Other Current Liabilities, Total',
    'IQ_DEF_TAX_LIAB_CURRENT': 'Deferred Tax Liability, Current',
    'IQ_TOTAL_CL': 'Total Current Liabilities',
    'IQ_LT_DEBT': 'Long-Term Debt',
    'IQ_OTHER_LIAB': 'Other Liabilities, Total',
    'IQ_OTHER_LIAB_LT': 'Other Non-Current Liabilities',
    'IQ_TOTAL_LIAB': 'Total Liabilities',
    'IQ_PREF_EQUITY': 'Total Preferred Equity',
    'IQ_COMMON': 'Common Stock',
    'IQ_APIC': 'Additional Paid In Capital',
    'IQ_RE': 'Retained Earnings',
    'IQ_TREASURY_OTHER_EQUITY': 'Treasury Stock and Other',
    'IQ_TOTAL_COMMON_EQUITY': 'Total Common Equity',
    'IQ_MINORITY_INTEREST_TOTAL': 'Total Minority Interest',
    'IQ_TOTAL_EQUITY': 'Total Equity',
    'IQ_PERIODDATE_BS': 'Period Date, Balance Sheet',
    'IQ_TOTAL_OUTSTANDING_BS_DATE': 'Total Shares Outstanding on Balance Sheet Date',
    'IQ_TOTAL_DEBT': 'Total Debt',
    'IQ_NET_WORKING_CAP': 'Net Working Capital',
    'IQ_TOTAL_EMPLOYEES': 'Total Employees',
    'IQ_FULL_TIME': 'Full Time Employees',
    'IQ_PART_TIME': 'Part-Time Employees',
    'IQ_FILING_CURRENCY': 'Filing Currency',
    'IQ_ST_DEBT_ISSUED': 'Short Term Debt Issued',
    'IQ_LT_DEBT_ISSUED': 'Long-Term Debt Issued',
    'IQ_TOTAL_DEBT_ISSUED': 'Total Debt Issued',
    'IQ_ST_DEBT_REPAID': 'Short Term Debt Issued',
    'IQ_LT_DEBT_REPAID': 'Long-Term Debt Issued',
    'IQ_TOTAL_DEBT_REPAID': 'Total Debt Repaid',
    'IQ_COMMON_ISSUED': 'Issuance of Common Stock',
    'IQ_COMMON_REP': 'Repurchase of Common Stock',
    'IQ_PREF_ISSUED': 'Issuance of Preferred Stock',
    'IQ_PREF_REP': 'Repurchase of Preferred Stock',
    'IQ_COMMON_DIV_CF': 'Common Dividends Paid',
    'IQ_TOTAL_DIV_PAID_CF': 'Total Dividends Paid',
    'IQ_SOURCE': 'Source Document',
    'IQ_FIN_DATA_SOURCE': 'Financials Data Provider'
}